apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Chart.Name }}-{{ .Chart.Version }}
 {{- include "spring.labels" . }}     
 spec:
  selector:
   {{- include "spring.labels" . | nindent 2 }}
 replicas:  {{ .Values.database_prod.repNum }}
 template:
   metadata:
     {{- include "spring.labels" . | nindent 4 }}
   spec:
     containers:
     - name:  {{ .Chart.Name }}
       image:  {{ .Values.pods.image }}
       ports:
         - containerPort: 8080
           name: http
           protocol: TCP
